// 검증 규칙 상수
const VALIDATION_RULES = {
  // 시간 관련
  MIN_HOURS_PER_WEEK: 0.167,  // 10분
  MAX_HOURS_PER_WEEK: 10,
  DEFAULT_MIN_HOURS_PER_WEEK: 3,
  DEFAULT_NUM_WEEKS: 4,
  DEFAULT_MIN_CLASS_DURATION_MINUTES: 60,

  // 자동 확정 기간
  MIN_AUTO_CONFIRM_DURATION: 1,
  MAX_AUTO_CONFIRM_DURATION: 168,  // 1주일

  // 재시도 설정
  MAX_RETRIES: 3,
  MAX_USER_SAVE_RETRIES: 5,
};

// 기본값
const DEFAULTS = {
  MIN_HOURS_PER_WEEK: 3,
  NUM_WEEKS: 4,
  TRANSPORT_MODE: 'normal',
  MIN_CLASS_DURATION_MINUTES: 60,
  ASSIGNMENT_MODE: 'normal',
};

module.exports = {
  VALIDATION_RULES,
  DEFAULTS,
};
